server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.177:3306/ysbg?characterEncoding=UTF-8
    username: joey
    password: 17520
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间
      idle-timeout: 1800000
      # 最大连接数 10
      maximum-pool-size: 10
      # 从连接池返回连接自动提交
      auto-commit: true
      # 连接最大存活时间 默认是1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认是30000(30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  main:
    allow-circular-references: true   # 循环依赖问题

  mvc:
    pathmatch:  # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher

  # RabbitMQ配置
  rabbitmq:
    # 用户名
    username: joey
    # 密码
    password: joey
    # 服务器地址
    host: 192.168.0.177
    # 端口号
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true

  redis:
    # 超时时间
    timeout: 10000
    # 服务器地址
    host: 192.168.0.177
    # 服务器端口
    port: 6379
    # 服务器密码
    password: 17520
    # 默认数据库
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 5
#    jedis:
#      pool:
#        min-idle: 5
#        max-active: 10
#        max-idle: 10
#        max-wait: 2000

# mybatis-plus设置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis-plus数据返回类型别名（默认的别名是类名）
  type-aliases-package: com.example.server
  configuration:
    # 关闭自定义驼峰命名
    map-underscore-to-camel-case: false

# mybatis SQL 打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.server.mapper: debug

# jwt 配置
jwt:
  # jwt 储存的请求头
  tokenHeader: Authorization
  # jwt 加解密使用的秘钥
  secret: ysbg-secret
  # jwt 超期限时间(24小时)
  expiration: 604800
  # jwt 负载中拿到的开头
  tokenHead: Bearer
